from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors
from datetime import datetime


def generate_student_report(student_name, scores, avg, risk, insights=None):
    """
    Generates a professional student performance report PDF
    """

    filename = f"{student_name}_report.pdf"
    doc = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()
    content = []

    # =========================
    # TITLE SECTION
    # =========================
    content.append(Paragraph("📊 EduTrack Student Performance Report", styles["Title"]))
    content.append(Spacer(1, 12))

    content.append(Paragraph(f"<b>Student Name:</b> {student_name}", styles["Normal"]))
    content.append(Paragraph(f"<b>Generated Date:</b> {datetime.now().strftime('%Y-%m-%d')}", styles["Normal"]))
    content.append(Spacer(1, 12))

    # =========================
    # SUMMARY SECTION
    # =========================
    content.append(Paragraph("📌 Performance Summary", styles["Heading2"]))
    content.append(Spacer(1, 6))

    content.append(Paragraph(f"<b>Average Score:</b> {avg:.2f}", styles["Normal"]))
    content.append(Paragraph(f"<b>Risk Level:</b> {risk}", styles["Normal"]))
    content.append(Spacer(1, 12))

    # =========================
    # AI INSIGHTS SECTION (NEW)
    # =========================
    if insights:
        content.append(Paragraph("🧠 AI Insights", styles["Heading2"]))
        content.append(Spacer(1, 6))

        for line in insights.split("\n"):
            content.append(Paragraph(f"• {line}", styles["Normal"]))

        content.append(Spacer(1, 12))

    # =========================
    # SCORES TABLE SECTION
    # =========================
    content.append(Paragraph("📚 Detailed Scores", styles["Heading2"]))
    content.append(Spacer(1, 6))

    data = [["Subject", "Score", "Date"]]

    for s in scores:
        data.append([str(s[1]), str(s[2]), str(s[3])])

    table = Table(data)

    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.darkblue),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 11),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("BACKGROUND", (0, 1), (-1, -1), colors.beige),
    ]))

    content.append(table)

    # =========================
    # FOOTER
    # =========================
    content.append(Spacer(1, 20))
    content.append(Paragraph("Generated by EduTrack Lite System", styles["Italic"]))

    doc.build(content)

    return filename


def generate_all_students_report(students_data):
    """
    Generate one PDF containing ALL students reports
    students_data = list of dicts:
    {
        "name": str,
        "scores": list,
        "avg": float,
        "risk": str,
        "insights": str
    }
    """

    filename = "all_students_report.pdf"
    doc = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()
    content = []

    # =========================
    # GLOBAL TITLE
    # =========================
    content.append(Paragraph("📊 EduTrack - Full Students Report", styles["Title"]))
    content.append(Spacer(1, 20))

    for student in students_data:

        # =========================
        # STUDENT HEADER
        # =========================
        content.append(Paragraph(f"<b>Student:</b> {student['name']}", styles["Heading2"]))
        content.append(Spacer(1, 6))

        content.append(Paragraph(f"Average Score: {student['avg']:.2f}", styles["Normal"]))
        content.append(Paragraph(f"Risk Level: {student['risk']}", styles["Normal"]))
        content.append(Spacer(1, 6))

        # =========================
        # INSIGHTS
        # =========================
        if student["insights"]:
            for line in student["insights"].split("\n"):
                content.append(Paragraph(f"• {line}", styles["Normal"]))

            content.append(Spacer(1, 10))

        # =========================
        # TABLE
        # =========================
        data = [["Subject", "Score", "Date"]]

        for s in student["scores"]:
            data.append([str(s[1]), str(s[2]), str(s[3])])

        table = Table(data)

        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.darkblue),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
            ("ALIGN", (0, 0), (-1, -1), "CENTER"),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ]))

        content.append(table)

        # =========================
        # PAGE BREAK BETWEEN STUDENTS
        # =========================
        from reportlab.platypus import PageBreak
        content.append(PageBreak())

    doc.build(content)

    # =========================
    # 🏆 TOP 3 LEADERBOARD
    # =========================
    sorted_students = sorted(
        students_data,
        key=lambda x: x["avg"],
        reverse=True
    )

    top3 = sorted_students[:3]

    content.append(Paragraph("🏆 Top 3 Students", styles["Heading2"]))
    content.append(Spacer(1, 10))

    leaderboard_data = [["Rank", "Student", "Average"]]

    ranks = ["🥇", "🥈", "🥉"]

    for i, student in enumerate(top3):
        leaderboard_data.append([
            ranks[i],
            student["name"],
            f"{student['avg']:.2f}"
        ])

    leaderboard_table = Table(leaderboard_data)

    leaderboard_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.darkgreen),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
    ]))

    content.append(leaderboard_table)
    content.append(Spacer(1, 20))

    return filename